# Explore Season Data
The purpose of this notebook is to explore the seasnal record data provided in the `records_history.csv` file and plan for data manipulation to be completed as part of pre-processing.

In [2]:
# Import relevant libraries
import pandas as pd

c:\Users\joseg\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
# Load end-of-seasson data
df = pd.read_csv('../data/records_history.csv')
df

,Manager,Year,Wins,Losses,Ties,Playoff_Wins,Playoff_Losses,Champion,Runner_Up,Last_Place,Scoring_Title
0,Dane Leone,2004,7,8,0,0,0,0,1,0,0
1,Dylan Leone,2004,11,4,0,0,0,0,0,1,0
2,Alec Gall,2004,11,4,0,1,0,1,0,0,1
3,Richard Easter,2004,1,14,0,0,0,0,0,0,0
4,Zach Iezzi,2004,7,8,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
188,Jarrod,2023,8,6,0,1,1,0,0,0,0
189,Joe Gamber,2023,7,6,1,0,0,0,0,0,0
190,Ryan Zabrosky,2023,7,6,1,2,1,0,1,0,0
191,Hayden Campbell,2023,9,5,0,2,0,1,0,0,0
192,Tyler Hendrick,2023,3,11,0,0,0,0,0,1,0

In [7]:
atr_df = df.groupby(by = ['Manager'])[['Wins', 'Losses', 'Ties']].sum()
atr_df['win_pct'] = (atr_df['Wins'] + 0.5*atr_df['Ties']) / (atr_df['Wins'] + atr_df['Losses'] + atr_df['Ties'])

atr_df.sort_values(by = 'win_pct', ascending=False)

                   Wins  Losses  Ties   win_pct
Manager
Hayden Campbell       9       5     0  0.642857
Ryan Leonard         17      11     0  0.607143
Alec Harvat          57      37     0  0.606383
Chandler Crusan      87      59     0  0.595890
Joe Gamber           91      67     1  0.575472
Alex Malinsky        30      24     2  0.553571
Korey Leonard        60      49     2  0.549550
Alec Gall            22      19     2  0.534884
Dylan Leone         142     128     2  0.525735
Dane Leone          120     110     3  0.521459
Harrison Campbell   130     122     5  0.515564
Tyler Hendrick       81      78     0  0.509434
Jarrod               47      47     0  0.500000
Ryan Zabrosky       125     128     4  0.494163
Bob Gamber           68      78     0  0.465753
Zach Iezzi           26      31     0  0.456140
Ryan Trout           11      15     0  0.423077
Alex DeCoste         23      32     0  0.418182
Richard Easter       45      66     2  0.407080
Brent Zabrosky       33      49     1  0.403614
Nathan Scheurman     15      23     1  0.397436
Alex (Harrison)      10      16     0  0.384615
Brennan Hoffer       22      41     1  0.351562
Todd Ulmer            7      19     0  0.269231
Kayla Jenner         13      41     0  0.240741

In [5]:
df.groupby(by = ['Manager'])[['Champion', 'Runner_Up', 'Last_Place', 'Scoring_Title']].sum().sort_values(by = ['Champion', 'Runner_Up'], ascending=False)

                   Champion  Runner_Up  Last_Place  Scoring_Title
Manager
Dylan Leone               3          2           2              2
Joe Gamber                3          0           1              3
Dane Leone                2          1           2              2
Richard Easter            2          0           0              1
Tyler Hendrick            2          0           2              2
Ryan Zabrosky             1          6           4              2
Alec Gall                 1          1           0              1
Bob Gamber                1          1           0              1
Harrison Campbell         1          1           0              1
Korey Leonard             1          1           0              1
Alex Malinsky             1          0           1              2
Brent Zabrosky            1          0           1              0
Hayden Campbell           1          0           0              0
Chandler Crusan           0          3           0              1
Alec Harvat               0          1           0              1
Brennan Hoffer            0          1           0              0
Jarrod                    0          1           1              0
Ryan Leonard              0          1           0              0
Alex (Harrison)           0          0           0              0
Alex DeCoste              0          0           1              0
Kayla Jenner              0          0           2              0
Nathan Scheurman          0          0           0              0
Ryan Trout                0          0           0              0
Todd Ulmer                0          0           1              0
Zach Iezzi                0          0           1              0